---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_RANDOM_ROOT_PASSWORD
        value: 'yes'
      - name: MYSQL_DATABASE
        value: 925r
      - name: MYSQL_USER
        value: 925r
      - name: MYSQL_PASSWORD
        value: veryunsecure
    ports:
    - containerPort: 3306
